version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: department-postgres-container
    environment:
      POSTGRES_DB: department
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pw4department
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
